# Generated by Django 4.1.7 on 2023-08-23 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='jdate',
        ),
    ]
