# Generated by Django 4.1.7 on 2023-08-24 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='age',
        ),
    ]
