# Generated by Django 4.1.7 on 2023-08-24 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_details_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='jdate',
        ),
    ]
